databases:
  - name: app_production_88a4
    databaseName: app_production_88a4
    user: app_production_88a4_user
    plan: free

services:
  - type: web
    name: app_web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: rails db:create rails db:migrate bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
